from day11 import Space

# ----------- Part 1 ------------

def test_part12_1() -> None:
    test_string = '''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''
    test_input = Space(test_string)
    p1, p2 = test_input.get_distance_sum(2, 10)
    assert p1 == 374
    assert p2 == 1030

def test_part12_2() -> None:
    test_string = '''...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....'''
    test_input = Space(test_string)
    p1, p2 = test_input.get_distance_sum(2, 100)
    assert p1 == 374
    assert p2 == 8410
