from day08 import Antennas

# ----------- Part 1 ------------

def test_parts1_2_1() -> None:
    test_string = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''
    test_input = Antennas(test_string)
    p1, p2 = test_input.get_antinode_counts()
    assert p1 == 14
    assert p2 == 34
